spring.application.name=BayPal

# =========================
# Database
# =========================
# Adds a default local fallback after the colon
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/baypal}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

# MySQL driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver